// <auto-generated />
using System;
using HRLeaveManagement.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRLeaveManagement.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241213205402_MakeDepartmentLeaderPropNullable")]
    partial class MakeDepartmentLeaderPropNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Responsibilities")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId")
                        .IsUnique();

                    b.HasIndex("SectionId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.EmployeeContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ExpiredAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeContracts", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeContract_TotalDuration_GreaterThanZero", "[TotalDuration] IS NULL OR [TotalDuration] > 0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.EmployeeEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EducationType")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EnrolledAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("GraduatedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.EmployeeExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EmployedFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EmployedTo")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalEmployment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeExperiences", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeExperience_TotalEmployment_GreaterThanZero", "[TotalEmployment] > 0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.LeaveAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailableDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<int?>("UsedDays")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveAllocations", t =>
                        {
                            t.HasCheckConstraint("CK_LeaveAllocation_AvailableDays_GreaterThanOrEqualToZero", "[AvailableDays] IS NULL OR [AvailableDays] >= 0");

                            t.HasCheckConstraint("CK_LeaveAllocation_RemainingDays_FewerThanOrEqualToAvailableDays", "[RemainingDays] IS NULL OR [RemainingDays] <= [AvailableDays]");

                            t.HasCheckConstraint("CK_LeaveAllocation_UsedDays_FewerThanOrEqualToAvailableDays", "[UsedDays] IS NULL OR [UsedDays] <= [AvailableDays]");

                            t.HasCheckConstraint("CK_LeaveAllocation_Year_GreaterThanOrEqualToCurrent", "[Year] >= YEAR(GETDATE())");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateOnly>("EndedAt")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestingEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubstitutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("RequestingEmployeeId");

                    b.HasIndex("SubstitutorId");

                    b.ToTable("LeaveRequests", t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequest_EndedAt_GreaterThanOrEqualToStartedAt", "[EndedAt] >= StartedAt");

                            t.HasCheckConstraint("CK_LeaveRequest_StartedAt_GreaterThanOrEqualToToday", "[StartedAt] >= CAST(GETDATE() AS date)");

                            t.HasCheckConstraint("CK_LeaveRequest_TotalDays_GreaterThanZero", "[TotalDays] > 0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PaidFraction")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes", t =>
                        {
                            t.HasCheckConstraint("LeaveType_PaidFraction_BetweenZeroAndOne", "[PaidFraction] BETWEEN 0.0 AND 1.0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.RemoteWorkLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RemoteWorkLimits", t =>
                        {
                            t.HasCheckConstraint("CK_RemoteWorkLimit_AvailableDays_GreaterThanOrEqualToZero", "[AvailableDays] >= 0");

                            t.HasCheckConstraint("CK_RemoteWorkLimit_RemainingDays_FewerThanOrEqualToAvailableDays", "[RemainingDays] <= [AvailableDays]");

                            t.HasCheckConstraint("CK_RemoteWorkLimit_UsedDays_FewerThanOrEqualToAvailableDays", "[UsedDays] <= [AvailableDays]");

                            t.HasCheckConstraint("CK_RemoteWorkLimit_Year_GreaterThanOrEqualToCurrent", "[Year] >= YEAR(GETDATE())");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.TimeRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("BreakEndedAt")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BreakStartedAt")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("TotalBreakTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalWorkTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WorkEndedAt")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WorkStartedAt")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeRegisters");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.WorkRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndedAt")
                        .HasColumnType("date");

                    b.Property<Guid>("RequestingEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestingEmployeeId");

                    b.ToTable("WorkRequests", t =>
                        {
                            t.HasCheckConstraint("CK_WorkRequest_EndedAt_GreaterThanOrEqualToStartedAt", "[EndedAt] >= [StartedAt]");

                            t.HasCheckConstraint("CK_WorkRequest_StartedAt_GreaterThanOrEqualToToday", "[StartedAt] >= CAST(GETDATE() AS date)");

                            t.HasCheckConstraint("CK_WorkRequest_TotalDays_GreaterThanOrEqualToZero", "[TotalDays] >= 0");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.DelegationRequest", b =>
                {
                    b.HasBaseType("HRLeaveManagement.Domain.Entities.WorkRequest");

                    b.Property<decimal>("CashAdvance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MeansOfTransport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PurposeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubstitutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SubstitutorId");

                    b.ToTable("DelegationRequests", t =>
                        {
                            t.HasCheckConstraint("CK_WorkRequest_EndedAt_GreaterThanOrEqualToStartedAt", "[EndedAt] >= [StartedAt]");

                            t.HasCheckConstraint("CK_WorkRequest_StartedAt_GreaterThanOrEqualToToday", "[StartedAt] >= CAST(GETDATE() AS date)");

                            t.HasCheckConstraint("CK_WorkRequest_TotalDays_GreaterThanOrEqualToZero", "[TotalDays] >= 0");

                            t.HasCheckConstraint("CK_DelegationRequest_CashAdvance_GreaterThanOrEqualToZero", "[CashAdvance] >= 0.0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.ExtraRemoteWorkRequest", b =>
                {
                    b.HasBaseType("HRLeaveManagement.Domain.Entities.WorkRequest");

                    b.Property<string>("ReasonDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.ToTable("ExtraRemoteWorkRequests", t =>
                        {
                            t.HasCheckConstraint("CK_WorkRequest_EndedAt_GreaterThanOrEqualToStartedAt", "[EndedAt] >= [StartedAt]");

                            t.HasCheckConstraint("CK_WorkRequest_StartedAt_GreaterThanOrEqualToToday", "[StartedAt] >= CAST(GETDATE() AS date)");

                            t.HasCheckConstraint("CK_WorkRequest_TotalDays_GreaterThanOrEqualToZero", "[TotalDays] >= 0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.OvertimeRequest", b =>
                {
                    b.HasBaseType("HRLeaveManagement.Domain.Entities.WorkRequest");

                    b.Property<string>("PurposeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.ToTable("OvertimeRequests", t =>
                        {
                            t.HasCheckConstraint("CK_WorkRequest_EndedAt_GreaterThanOrEqualToStartedAt", "[EndedAt] >= [StartedAt]");

                            t.HasCheckConstraint("CK_WorkRequest_StartedAt_GreaterThanOrEqualToToday", "[StartedAt] >= CAST(GETDATE() AS date)");

                            t.HasCheckConstraint("CK_WorkRequest_TotalDays_GreaterThanOrEqualToZero", "[TotalDays] >= 0");
                        });
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Department", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Leader")
                        .WithOne()
                        .HasForeignKey("HRLeaveManagement.Domain.Entities.Employee", "LeaderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.Section", "Section")
                        .WithOne()
                        .HasForeignKey("HRLeaveManagement.Domain.Entities.Employee", "SectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Leader");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.EmployeeContract", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("EmploymentContracts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.EmployeeEducation", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.EmployeeExperience", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeExperiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.LeaveAllocation", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "RequestingEmployee")
                        .WithMany()
                        .HasForeignKey("RequestingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Substitutor")
                        .WithMany()
                        .HasForeignKey("SubstitutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("LeaveType");

                    b.Navigation("RequestingEmployee");

                    b.Navigation("Substitutor");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.RemoteWorkLimit", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Section", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.TimeRegister", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.WorkRequest", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "RequestingEmployee")
                        .WithMany()
                        .HasForeignKey("RequestingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("RequestingEmployee");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.DelegationRequest", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.WorkRequest", null)
                        .WithOne()
                        .HasForeignKey("HRLeaveManagement.Domain.Entities.DelegationRequest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRLeaveManagement.Domain.Entities.Employee", "Substitutor")
                        .WithMany()
                        .HasForeignKey("SubstitutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Substitutor");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.ExtraRemoteWorkRequest", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.WorkRequest", null)
                        .WithOne()
                        .HasForeignKey("HRLeaveManagement.Domain.Entities.ExtraRemoteWorkRequest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.OvertimeRequest", b =>
                {
                    b.HasOne("HRLeaveManagement.Domain.Entities.WorkRequest", null)
                        .WithOne()
                        .HasForeignKey("HRLeaveManagement.Domain.Entities.OvertimeRequest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("HRLeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeEducations");

                    b.Navigation("EmployeeExperiences");

                    b.Navigation("EmploymentContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
